import 'package:flutter/material.dart';
import 'package:expense_tracker/models/folder_model.dart';
import 'package:expense_tracker/models/file_model.dart';
import 'package:expense_tracker/services/storage_service.dart';
import 'package:expense_tracker/services/auth_service.dart';
import 'dart:io';

class StorageProvider with ChangeNotifier {
  final StorageService _storageService = StorageService();
  final AuthService _authService = AuthService();

  // Streams are excellent for Firestore real-time updates
  // We can expose Stream getters or manage lists manually.
  // Given the UI uses simple lists, StreamBuilder in UI is easiest, 
  // or we can listen to streams here and update lists.
  // For simplicity and "Provider" pattern, let's expose Streams.

  Stream<List<FolderModel>> get userFoldersStream {
    final user = _authService.currentUser;
    if (user == null) {
      return Stream.value([]);
    }
    return _storageService.getFolders(user.uid);
  }
  
  Stream<List<FolderModel>> getSubFoldersStream(String parentId) {
    final user = _authService.currentUser;
    if (user == null) {
      return Stream.value([]);
    }
    return _storageService.getFolders(user.uid, parentId: parentId);
  }

  Stream<List<FileModel>> get recentFilesStream {
    final user = _authService.currentUser;
    if (user == null) {
      return Stream.value([]);
    }
    return _storageService.getRecentFiles(user.uid);
  }

  Stream<List<FileModel>> getFilesInFolder(String folderId) {
    final user = _authService.currentUser;
    if (user == null) {
      print("StorageProvider: WARNING - User is null, returning empty stream for files.");
      return Stream.value([]);
    }
    // We pass userId to ensure security/path correctness if needed by service
    return _storageService.getFilesInFolder(user.uid, folderId);
  }

  // Action: Create Folder
  Future<void> createFolder(String name, {String? parentId}) async {
    print("StorageProvider: createFolder called with name: $name, parentId: $parentId");
    final user = _authService.currentUser;
    if (user == null) {
      print("StorageProvider: Error - Current user is null");
      return;
    }
    print("StorageProvider: User found: ${user.uid}");

    final newFolder = FolderModel(
      id: '', // Generated by Firestore
      userId: user.uid,
      name: name,
      createdAt: DateTime.now(),
      parentId: parentId,
      // Randomize color slightly or use logic
      color: '0xFF90CAF9', 
      iconAsset: 'assets/icons/folder_icon_v2.png',
    );

    await _storageService.createFolder(newFolder);
    print("StorageProvider: Folder creation complete, notifying listeners");
    notifyListeners();
  }

  // Action: Upload File
  Future<void> uploadFile(File file, String folderId, FileType type) async {
    print("StorageProvider: uploadFile called for folder: $folderId");
    final user = _authService.currentUser;
    if (user == null) return;

    try {
      // 1. Upload to Storage
      final downloadUrl = await _storageService.uploadFileToStorage(file, user.uid);
      
      // 2. Create Metadata
      final newFile = FileModel(
        id: '', // Generated
        userId: user.uid,
        folderId: folderId,
        name: file.path.split('/').last,
        type: type,
        url: downloadUrl,
        sizeInBytes: file.lengthSync(), // Store bytes
        createdAt: DateTime.now(),
        isStarred: false,
      );

      await _storageService.createFile(newFile);
      print("StorageProvider: File upload complete");
      notifyListeners();
    } catch (e) {
      print("StorageProvider: Error uploading file: $e");
      rethrow;
    }
  }

  // Action: Delete File
  Future<void> deleteFile(FileModel file) async {
    print("StorageProvider: deleteFile called for: ${file.id}");
    try {
      await _storageService.deleteFile(file.id, file.url, file.folderId, file.sizeInBytes);
      print("StorageProvider: File deletion complete");
      notifyListeners();
    } catch (e) {
      print("StorageProvider: Error deleting file: $e");
      rethrow;
    }
  }

  // Action: Sync Folder Stats
  Future<void> syncFolderStats() async {
    final user = _authService.currentUser;
    if (user == null) return;
    
    try {
      await _storageService.recalculateFolderStats(user.uid);
      notifyListeners();
    } catch (e) {
      print("StorageProvider: Error syncing stats: $e");
      rethrow;
    }
  }
}
